name: main on CLN v24.02.2

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'Dockerfile'
            - '*.md'
            - 'LICENSE'
            - '.gitignore'
            - 'coffee.yml'
            - '*.sh'
            - 'lnd.py'
    pull_request:
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v24.02.2"
            pyln-version: "24.02"
            tagged-release: false